In [5]:
import numpy as np
from scipy.stats import norm

# Define the correlation matrix
corr_mat = np.array([[1.0, 0.5, 0.3, 0.2],
                     [0.5, 1.0, 0.4, 0.1],
                     [0.3, 0.4, 1.0, 0.6],
                     [0.2, 0.1, 0.6, 1.0]])

# Define the mean vector
mean_vec = np.array([2.0, 1.5, 3.0, 2.5])

# Define the standard deviation vector
std_vec = np.array([0.5, 0.6, 0.7, 0.8])

# Define the joint distribution function
def joint_distribution(x):
    return norm.cdf(x, loc=mean_vec, scale=std_vec)

# Define the inverse joint distribution function
def inverse_joint_distribution(x):
    return norm.ppf(x, loc=mean_vec, scale=std_vec)

# Define the Nataf transformation function
def nataf_transform(x):
    # Calculate the correlation matrix's Cholesky decomposition
    L = np.linalg.cholesky(corr_mat)
    
    # Transform the input vector to the standard normal space
    z = np.linalg.solve(L, x - mean_vec)
    
    # Calculate the correlation matrix's determinant
    det = np.linalg.det(corr_mat)
    
    # Calculate the transformed vector
    y = inverse_joint_distribution(joint_distribution(z) * (1 / np.sqrt(det)))
    
    return y

# Generate synthetic data using the Nataf transformation
n_samples = 2000

# Generate random samples in the standard normal space
z_samples = np.random.randn(n_samples, 4)

# Transform the samples using the Nataf transformation
x_samples = np.zeros((n_samples, 4))
for i in range(n_samples):
    x_samples[i] = nataf_transform(z_samples[i])

# Print the first 10 samples
print(x_samples[:10])


[[-1.9310965  -1.18211888 -1.97443638 -1.05689261]
 [-1.87057672  0.700364   -2.50301449 -1.46781978]
 [-1.51285501 -0.80642546 -2.46701411 -1.08828636]
 [-2.89252522 -1.12991639 -2.4970384  -2.22400903]
 [-1.61815011  0.3040655  -2.52943888  0.4262187 ]
 [-1.55607383  0.49302017 -3.40406919 -0.41302049]
 [-1.85311381  0.56664784 -2.39829377  2.49487217]
 [-3.10051645  1.40140394 -4.04470461  0.87403607]
 [-1.25303454 -1.19943745 -2.56951146 -0.47479241]
 [-2.19515965 -0.15106296 -2.39884468 -1.12590195]]


In [4]:
# NaTaf for 
import numpy as np
from scipy.stats import norm, lognorm, expon, chi2, uniform

# Define the correlation matrix
corr_mat = np.array([[1.0, 0.5, 0.3, 0.2, -0.1],
                     [0.5, 1.0, 0.4, 0.1, -0.2],
                     [0.3, 0.4, 1.0, 0.6, 0.2],
                     [0.2, 0.1, 0.6, 1.0, -0.3],
                     [-0.1, -0.2, 0.2, -0.3, 1.0]])

# Define the mean vector
mean_vec = np.array([2.0, 1.5, 3.0, 2.5, 1.0])

# Define the standard deviation vector
std_vec = np.array([0.5, 0.6, 0.7, 0.8, 0.9])

# Define the joint distribution function
def joint_distribution(x):
    y1 = norm.cdf(x[0], loc=mean_vec[0], scale=std_vec[0])
    y2 = lognorm.cdf(x[1], s=std_vec[1], scale=np.exp(mean_vec[1]))
    y3 = expon.cdf(x[2], scale=mean_vec[2])
    y4 = chi2.cdf(x[3], df=mean_vec[3])
    y5 = uniform.cdf(x[4], loc=mean_vec[4] - np.sqrt(3)*std_vec[4], scale=2*np.sqrt(3)*std_vec[4])
    return np.array([y1, y2, y3, y4, y5])

# Define the inverse joint distribution function
def inverse_joint_distribution(x):
    y1 = norm.ppf(x[0], loc=mean_vec[0], scale=std_vec[0])
    y2 = lognorm.ppf(x[1], s=std_vec[1], scale=np.exp(mean_vec[1]))
    y3 = expon.ppf(x[2], scale=mean_vec[2])
    y4 = chi2.ppf(x[3], df=mean_vec[3])
    y5 = uniform.ppf(x[4], loc=mean_vec[4] - np.sqrt(3)*std_vec[4], scale=2*np.sqrt(3)*std_vec[4])
    return np.array([y1, y2, y3, y4, y5])

# Define the Nataf transformation function
def nataf_transform(x):
    # Calculate the correlation matrix's Cholesky decomposition
    L = np.linalg.cholesky(corr_mat)
    
    # Transform the input vector to the standard normal space
    z = np.linalg.solve(L, x - mean_vec)
    
    # Calculate the correlation matrix's determinant
    det = np.linalg.det(corr_mat)
    
    # Calculate the transformed vector
    y = inverse_joint_distribution(joint_distribution(z) * (1 / np.sqrt(det)))
    
    return y

# Generate synthetic data using the Nataf transformation
n_samples = 10000

# Generate random samples in the standard normal space
z_samples = np.random.randn(n_samples, 5)

# Transform the samples using the Nataf transformation
x_samples = np.zeros((n_samples, 5))
for i in range(n_samples):
    x_samples[i] = nataf_transform(z_samples[i])

# Print the first 10 samples
print(x_samples[:10])

[[-0.28403711  0.35330365  0.          0.         -0.55884573]
 [-2.82694139  0.          0.          0.         -0.55884573]
 [-1.78518705  0.61775645  0.          0.          1.2653274 ]
 [-1.64559039  0.          0.          1.35622479 -0.55884573]
 [-3.05907477  0.12659623  0.          2.01961998 -0.55884573]
 [-3.91930674  0.          0.          0.         -0.55884573]
 [-2.27353759  0.69647644  0.          1.41658998 -0.16804434]
 [-1.98451144  0.          0.          0.91244996         nan]
 [-2.3687235   0.41273703  0.          2.10555204         nan]
 [-2.58456534  0.51319377  0.          0.         -0.55884573]]
